[manifest]
version = "1.0.0"
priority = 10

# Replace New Run button on game win with Quit button (if "quit on win" is enabled)
[[patches]]
[patches.pattern]
target = "functions/UI_definitions.lua"
pattern = "        not show_win_cta and UIBox_button({id = 'from_game_won', button = 'notify_then_setup_run', label = {localize('b_start_new_run')}, minw = 2.5, maxw = 2.5, minh = 1, focus_args = {nav = 'wide', snap_to = true}}) or nil,"
position = "at"
payload = "        not show_win_cta and UIBox_button({id = 'from_game_won', button = GTB.WINBUTTON(), label = {localize(GTB.WINLABEL())}, minw = 2.5, maxw = 2.5, minh = 1, focus_args = {nav = 'wide', snap_to = true}}) or nil,"
match_indent = true

# Same at game over
[[patches]]
[patches.pattern]
target = "functions/UI_definitions.lua"
pattern = '''          {n=G.UIT.R, config={id = 'from_game_over', align = "cm", minw = 5, padding = 0.1, r = 0.1, hover = true, colour = G.C.RED, button = "notify_then_setup_run", shadow = true, focus_args = {nav = 'wide', snap_to = true}}, nodes={
            {n=G.UIT.R, config={align = "cm", padding = 0, no_fill = true, maxw = 4.8}, nodes={
              {n=G.UIT.T, config={text = localize('b_start_new_run'), scale = 0.5, colour = G.C.UI.TEXT_LIGHT}}
            }}
          }},'''
position = "at"
payload = '''          {n=G.UIT.R, config={id = 'from_game_over', align = "cm", minw = 5, padding = 0.1, r = 0.1, hover = true, colour = G.C.RED, button = GTB.DIEBUTTON(), shadow = true, focus_args = {nav = 'wide', snap_to = true}}, nodes={
            {n=G.UIT.R, config={align = "cm", padding = 0, no_fill = true, maxw = 4.8}, nodes={
              {n=G.UIT.T, config={text = localize(GTB.DIELABEL()), scale = 0.5, colour = G.C.UI.TEXT_LIGHT}}
            }}
          }},'''
match_indent = true